export const DISTRICT_TO_NEIGHBORHOODS = new Map<number, string[]>([
  [
    1,
    [
      "Barrio Logan",
      "Centre City",
      "Golden Hill",
      "Grant Hill",
      "Logan Heights",
      "Memorial",
      "Midway-Pacific Highway",
      "Sherman Heights",
      "Stockton",
    ],
  ],
  [
    2,
    [
      "Clairemont Mesa",
      "La Jolla",
      "Mission Bay Park",
      "Pacific Beach",
      "University City",
    ],
  ],
  [
    3,
    [
      "Balboa Park",
      "Bankers Hill",
      "City Heights",
      "Hillcrest",
      "Kensington-Talmadge",
      "Mission Hills",
      "Normal Heights",
      "North Park",
      "Old Town",
      "Uptown",
    ],
  ],
  [
    4,
    [
      "Chollas View",
      "College Area",
      "College East",
      "Eastern Area",
      "Encanto",
      "Jamacha-Lomita",
      "Mountain View",
      "Oak Park",
      "Skyline-Paradise Hills",
      "Valencia Park",
    ],
  ],
  [
    5,
    [
      "Black Mountain Ranch",
      "Carmel Mountain Ranch",
      "Del Mar Mesa",
      "Mira Mesa",
      "Pacific Highlands Ranch",
      "Rancho Bernardo",
      "Rancho Encantada",
      "Rancho Penasquitos",
      "Sabre Springs",
      "Torrey Hills",
      "Torrey Pines",
    ],
  ],
  [
    6,
    [
      "Kearny Mesa",
      "Linda Vista",
      "Miramar",
      "Miramar Ranch North",
      "Mission Valley",
      "Navajo",
      "San Carlos",
      "Serra Mesa",
      "Tierrasanta",
    ],
  ],
  [
    7,
    [
      "Del Cerro",
      "Lake Murray",
      "Allied Gardens",
      "Grantville",
      "Rolando",
    ],
  ],
  [
    8,
    [
      "Otay Mesa",
      "Otay Mesa-Nestor",
      "Palm City",
      "San Ysidro",
      "Tijuana River Valley",
    ],
  ],
  [
    9,
    ["Mid-City", "Southeastern San Diego"],
  ],
]);
